version: '3'
services:
  wordpress:
    build: .
    volumes:
      - .:/bedrock
    env_file: .env
    environment:
      WP_ENV: development
      WP_HOME: http://${SERVER_NAME}
      WP_SITEURL: http://${SERVER_NAME}/wp
      WP_LANG: en_GB
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
      DB_NAME: wordpress
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_HOST: mysql
    ports:
      - 80:80
    depends_on:
      - mysql
      - mailcatcher
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - database:/var/lib/mysql
  mailcatcher:
    image: schickling/mailcatcher
    environment:
      VIRTUAL_HOST: mail.${SERVER_NAME}
      VIRTUAL_PORT: 1080
volumes:
  database:
    driver: local
